site_name: organize
repo_url: https://github.com/tfeldmann/organize/
site_author: "Thomas Feldmann"
nav:
  - Home: index.md
  - Configuration: 01-config.md
  - Locations: 02-locations.md
  - Filters: 03-filters.md
  - Actions: 04-actions.md
  - Changelog: 05-changelog.md
  - Updating from organize v1.x: 06-updating-from-v1.md
plugins:
  - search
  - include-markdown
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            members: false
          rendering:
            show_bases: false
            show_root_toc_entry: false
            show_root_heading: false
            show_source: false
      watch:
        - organize

markdown_extensions:
  - toc:
      permalink: "#"

theme:
  name: readthedocs
