site_name: organize
repo_url: https://github.com/tfeldmann/organize/
site_author: "Thomas Feldmann"
nav:
  - Home: index.md
  - Configuration: configuration.md
  - Rules: rules.md
  - Locations: locations.md
  - Filters: filters.md
  - Actions: actions.md
  - Changelog: changelog.md
  - Updating from organize v1.x: updating-from-v1.md
plugins:
  - search
  - include-markdown
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            members: false
          rendering:
            show_bases: false
            show_root_toc_entry: false
            show_root_heading: false
            show_source: false
      watch:
        - .
        - organize

markdown_extensions:
  - toc:
      permalink: "#"
  - mkdocs-click

theme:
  name: readthedocs
